#!/bin/csh -f

set alt		= 0
set file	= ximtool.gui

alt:

echo -n "Building $file ..."
if ($alt == 0) then
    cat main.obj		> $file
else
    cat main-alt.obj		> $file
endif
cat panel.obj			>> $file
cat param.obj			>> $file
cat help.obj			>> $file
cat blink.obj			>> $file
cat hdr.obj			>> $file
cat pixtab.obj			>> $file
cat tcl.obj			>> $file
cat warn.obj			>> $file

if ($alt == 0) then
    cat main.res		>> $file
else
    cat main-alt.res		>> $file
endif
cat panel.res			>> $file
cat display.res			>> $file
cat print.res			>> $file
cat info.res			>> $file
cat load.res			>> $file
cat save.res			>> $file
cat tile.res			>> $file
cat wcs.res			>> $file
cat blink.res			>> $file
cat hdr.res			>> $file
cat pixtab.res			>> $file
cat help.res			>> $file
cat tcl.res			>> $file
cat warn.res			>> $file
cat global.res			>> $file
cat resources.res		>> $file

cat boot.tcl			>> $file
cat global.tcl			>> $file
cat plots.tcl			>> $file
cat imagewin.tcl		>> $file
cat func.tcl			>> $file
cat panel.tcl			>> $file
cat magnifier.tcl		>> $file
cat panner.tcl			>> $file
cat print.tcl			>> $file
cat info.tcl			>> $file
cat load.tcl			>> $file
cat save.tcl			>> $file
cat tile.tcl			>> $file
cat wcs.tcl			>> $file
cat compass.tcl			>> $file
cat rulers.tcl			>> $file
cat help.tcl			>> $file
cat hdr.tcl			>> $file
cat pixtab.tcl			>> $file
cat warn.tcl			>> $file
cat tcl.tcl			>> $file
cat ism.tcl			>> $file
if ($alt == 1) then
    cat alt.tcl			>> $file
endif

echo "Done"

if ($alt == 0) then
    set alt	= 1
    set file	= ximtool-alt.gui
    goto alt
endif

echo -n "Installing files ..."
mv *.gui ../
echo "Done"
